# Generated by Django 4.2.7 on 2023-12-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
