# Generated by Django 4.2.7 on 2023-12-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.CharField(default='default.png', max_length=50),
        ),
    ]
